[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/shop/order-confirmed"
  to = "/shop/order-confirmed.html"
  status = 200

[[redirects]]
  from = "/blog/post"
  to = "/blog/post.html"
  status = 200
